Algoritmo "Meu primeiro algoritmo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Beltrandes Marques dos Santos Neto)
// Data atual  : 07/02/2022
Var
// Seção de Declarações das variáveis 
   nota: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   nota <- 9999
   escreva("Resultado da nota:", nota)
Fimalgoritmo