Algoritmo "Variáveis"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Cleison Melo
// Descrição   : Variáveis
// Autor(a)    : Beltrandes Marques
// Data atual  : 07/02/2022
Var
// Seção de Declarações das variáveis 
//primeiro nome
//segundo nome
//idade
//cidade
//endereço

          primeiroNome, segundoNome, cidade, endereco: caractere
          idade: inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo